/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Todo,
} from './components/todo-list/todo-list';

declare global {

  namespace StencilComponents {
    interface TodoSite {

    }
  }

  interface HTMLTodoSiteElement extends StencilComponents.TodoSite, HTMLStencilElement {}

  var HTMLTodoSiteElement: {
    prototype: HTMLTodoSiteElement;
    new (): HTMLTodoSiteElement;
  };
  interface HTMLElementTagNameMap {
    'todo-site': HTMLTodoSiteElement;
  }
  interface ElementTagNameMap {
    'todo-site': HTMLTodoSiteElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'todo-site': JSXElements.TodoSiteAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoSiteAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface TodoForm {

    }
  }

  interface HTMLTodoFormElement extends StencilComponents.TodoForm, HTMLStencilElement {}

  var HTMLTodoFormElement: {
    prototype: HTMLTodoFormElement;
    new (): HTMLTodoFormElement;
  };
  interface HTMLElementTagNameMap {
    'todo-form': HTMLTodoFormElement;
  }
  interface ElementTagNameMap {
    'todo-form': HTMLTodoFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'todo-form': JSXElements.TodoFormAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoFormAttributes extends HTMLAttributes {
      'onNewTodo'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface TodoList {
      'todos': Todo[];
    }
  }

  interface HTMLTodoListElement extends StencilComponents.TodoList, HTMLStencilElement {}

  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };
  interface HTMLElementTagNameMap {
    'todo-list': HTMLTodoListElement;
  }
  interface ElementTagNameMap {
    'todo-list': HTMLTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'todo-list': JSXElements.TodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoListAttributes extends HTMLAttributes {
      'onToggleTodo'?: (event: CustomEvent) => void;
      'todos'?: Todo[];
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
